### ISSUE TITLE
Add/modify Software page

### ISSUE THREAD

**Issue by bjoyce3** [uabrc/uabrc.github.io#217]
Licensed software:
MatLab - UAB site license
Ansysi - Eng license and only Eng group members allowed to use it
LS-Dyna - Eng license
Gorubi - That one user that requested license, free by request
Parabricks - 2 GPU license paid 1 yr by RC
SAS - UAB site license
SPSS - UAB site license

Consider pulling software modules from Cheaha some how...there's a whole lotta them

**Comment by wwarriner** [comment]
Good idea for a page.

I'm hesitant to just dump all the modules into a page this way. Licensed software and a blurb about who they are available for, etc., makes sense sure. But as for all software everywhere, we might want to think of having a means of searching them in a more natural way, rather than a giant table.

After all, anyone with an account can log in and search! So maybe just start with that part.

My proposal for sections:

1. How to locate software on Cheaha
2. Restricted software (think of a better wording)
3. What to do if the software I want isn't on Cheaha
