### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by mdefende** [uabrc/uabrc.github.io#34]
ReadTheDocs had a much larger space above the Navigation menu for branding, so the current logo there fit fine and was readable. This is not the case for MkDocs. When testing out the logo feature, the image was shrunk down to an unreadable size. Need to find a smaller, more minimalistic logo if we want branding at all.

**Comment by wwarriner** [comment]
I'll see if I can modify this in the stylesheet...

**Comment by wwarriner** [comment]
Here is a mockup from modifying the CSS. I think we discussed in slack that this will take more careful consideration and finding a better spot to put the logo.

![image](https://user-images.githubusercontent.com/6930772/153295195-fbb9b4fd-2bb1-484d-a68f-5ae8aeb6d3b4.png)

**Comment by wwarriner** [comment]
This issue has been open a fair amount of time. We've tried something and it doesn't work with our logo. I'm going to close this issue and we can revisit as needed with a new logo.

For posterity, Blaze is not allowed to be used for non-sports things (apparently?). Cheaha logo is inappropriate since this has larger scope than just Cheaha. We have a UAB IT RC logo, but it is either too large, or too hard to read at the native size of the top bar.
