### ISSUE TITLE
Add more notes and information about dos/donts with Anaconda on Cheaha

### ISSUE THREAD

**Issue by wwarriner** [uabrc/uabrc.github.io#562]
### What would you like to see added?

Taken straight from a ticket Matt and I responded to recently:

> Hi there, I'll add some thoughts from my personal experience with dealing with related Anaconda and python issues. Here is what I've observed on Cheaha:
>
> - `which python` can help diagnose whether you are using the python you believe you are using. If you run into strange python errors that we can't reproduce, this can be a helpful first step. If it doesn't point to where Matt said, i.e. something like `~/.conda/envs/remora/bin/python`, then that is a helpful clue that an unexpected version of python is being used.
>
> - Having custom installs of Anaconda, Miniconda, Mambaforge or Minimamba can cause the issue above, even when `module load Anaconda3` is used.
>
> - Using `conda init` and `mamba init` result in changes to your `.bashrc`, which Matt has pointed out. These changes cause a specific version of Python added to the _front_ of `$PATH` variable. The `$PATH` variable is how Linux finds executables matching what you type at the command line or use in a script. When you try to execute a command, Linux searches the `$PATH` variable entries, one at a time, in order from first to last. So if the first entry is to whatever is from the `mamba init` code in your `.bashrc`, that is the version of Python that will get used.
>
> - Don't use `mamba init` or `conda init` on Cheaha. They interfere with the function of various Open OnDemand applications in a way that can be hard to diagnose.
>
> - Always start scripts with `module reset` to get a clean environment.
>
> I highly recommend what Matt suggested. Remove anything related to `mamba init` from `.bashrc` (the last several lines starting with `# >>> conda initialize >>>` and ending with `# <<< conda initialize <<< `, including those lines). Please also remove your custom installation of Mambaforge, and any installations of other Anaconda products, and please use only `module load Anaconda3` and `module load Mamba`. If you encounter issues with either please let us know and we will work to resolve them.
>
>If you need to move environments from your custom installation to our modules, see the following URL for instructions on how to do that: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#building-identical-conda-environments
>
>I see also that you have many `export $PATH` commands. I highly recommend not having those in your `.bashrc`. Every script you run will also export those path variables. If executable names collide with anything installed or loaded as a module, there can be hard-to-diagnose conflicts. Instead, if you have custom software, modify the `$PATH` variable within relevant scripts. If you find yourself doing this often, let us know and we can find a path forward to minimize friction.

Tutorial suggestion moved to #662

**Comment by wwarriner** [comment]
`mamba` is obsolete, we just use `module load Anaconda3` now.

**Comment by jgordini** [comment]
# ANACONDA ROUND TRIP

## Load the module

Before we start working with Anaconda, we need to reset all the loaded modules to avoid any conflicts. To do this, use the command:

```bash
module reset
```

After resetting, you can load the Anaconda module 

```bash
module load Anaconda3
```

## Create an environment

Anaconda environments are used to isolate different projects and their dependencies. For example, we could create an environment with the SciPy stack for data analysis. To create an environment, use:

```bash
conda create -n myenv
```

Replace 'myenv' with the name of your environment.

## Activate the environment

To use an environment, you have to activate it. Activating an environment modifies your PATH so that the versions of software installed in the environment can be used:

```bash
conda activate myenv
```

The base environment is the environment where Anaconda is installed, and it includes a bunch of useful libraries. When you activate another environment, such as the one we just created, the software installed in the base environment is not available unless it is also installed in the new environment.

## Install packages

You can install additional packages in your environment with the `conda install` command:

```bash
conda install numpy
```

This command installs the NumPy library in the currently active environment.

## Use the packages

You can now use the packages installed in your environment. For example, if you installed NumPy, you could start Python and do:

```python
import numpy as np
np.array([1, 2, 3])
```

## Create an env file for sharing on Cheaha

If you want to share your environment with others, you can export it to a YAML file:

```bash
conda env export > environment.yml
```

This file includes all the packages in your environment and can be used to recreate the environment.

## Create an env file for broader collaboration

For broader collaboration, such as sharing your environment on GitHub, you might want to create a more curated environment file that only includes the main dependencies of your project, excluding transitive dependencies and packages installed for personal use. You can manually create such a file. Here's an example:

```yaml
name: myenv
channels:
  - anaconda
dependencies:
  - numpy=1.21.5
  - scipy=1.7.1
```

## Delete the environment

If you no longer need an environment, you can remove it:

```bash
conda env remove --name myenv
```

## Create the environment from the env file

You can create a new environment from an environment file with:

```bash
conda env create -f environment.yml
```

This creates a new environment with the same packages as the original environment. This is useful for sharing your work with others, as they can recreate your environment and run your code without any dependency issues. 



# Running Jupyter Lab in a Browser using an SSH tunnel

First, open a terminal on your local machine.

## SSH into Cheaha:

```
ssh your_username@cheaha.rc.uab.edu -p22
```

Replace `your_username` with your actual Cheaha username. You will be prompted to enter your password. More information on seting up your Cheaha SSH session can be found here.

## Start a new tmux session:

```
tmux new -s jupyter
```

This starts a new tmux session named `jupyter`. You can replace `jupyter` with a different name if you prefer.

You can always SSH into Cheaha and check which tmux windows you have open by running `tmux` and pressing `Ctrl+b` followed by `s`. This will list the running windows. 

## Run Jupyter Lab on a partition in Cheaha

To run Jupyter Lab on the short partition in Cheaha, you can use a combination of the `srun` command (which is part of SLURM) and the `jupyter lab` command. Here is an example:

First, you need to request a session using `srun`. 

```
srun --partition=short --pty bash -l
```

This command requests an interactive session (`--pty bash -l`) on the short partition (`--partition=short`). You can choose any of the available partitions. 

```
module reset
module load Anaconda3
conda create -n myenv
jupyter lab --no-browser --ip=0.0.0.0
```

The `--no-browser` option prevents Jupyter Lab from trying to open a web browser, and the `--ip=0.0.0.0` option allows connections from any IP address.

This will start Jupyter Lab on port `8888` and display a URL that you can use to connect to it. The URL will look something like this: **Copy this url into a text file for future use**

```
http://c0172:8888/?token=your_token
```

Make a note of the partition number (`c0172` in this case), port number (`8888` in this case) and the token (`your_token`). 

Detach from the tmux session by pressing `Ctrl+b` followed by `d`. This will leave Jupyter Lab running in the background.

## Exit the SSH session:

```
exit
```

Now, you're back to your local machine's terminal.

## Set up the SSH tunnel

To set up an SSH tunnel to the Jupyter Lab, use  the following:

```
ssh -N -L localhost:8000:c0172:8888 your_username@cheaha.rc.uab.edu
```

In this command:

- `ssh` starts the SSH client.
- `-N` tells SSH that no command will be sent once the tunnel is up.
- `-L` specifies that the connections from the client should be forwarded to the server, then to the destination.
- `localhost:8000` is the local port that you will use to access Jupyter Lab in your web browser.
- `c0172:8888` is the remote port where Jupyter Lab is running on the server.
- `your_username@cheaha.rc.uab.edu` should be replaced with your actual username and the address of the remote server.

After running this command, you should be able to access the Jupyter Lab by opening your web browser and going to `http://localhost:8000/lab?token=YOUR TOKEN`.

Keep in mind that YOUR TOKEN (`dd616fc123c988812edbe1854ca884ebfb01e4fdb7693e7b`) is used for authentication and it will change each time Jupyter Lab is started. You should always use the current token provided by the Jupyter Lab server.

Remember, you need to keep the SSH command running as long as you're using the Jupyter Lab session. If you close it, the tunnel will also close and you'll lose access to Jupyter Lab. Alternatively you can set up a Tmux session locally and run it in the background. Using the above commands. 

If you encounter an error like:
```
bind [127.0.0.1]:8888: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: 8888
Could not request local forwarding.
```

The error message you're seeing indicates that the port `8888` on your local machine is already in use by another process. You can resolve this issue by choosing a different local port for the SSH tunnel.

For example, you could choose port `8889` (or any other available port) instead of `8888`.

**Comment by jgordini** [comment]
Wasn't sure where to put this.

**Comment by wwarriner** [comment]
We also want to warn folks to only use `pip` when in an Anaconda environment where `pip` is installed.

1. `module load Anaconda3`
1. Create/activate Anaconda env
1. `conda install pip`
1. Use `pip` from here.

If `pip` is used outside of Anaconda, or within an environment that does not have `pip` installed, then packages are installed to `~/.local`. Python loads packages from `~/.local` before loading from Anaconda environments, which can cause unexpected package conflicts.
